services:
  - type: web
    name: nexforce-ems
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application --timeout 120 --workers 1 --threads 2"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false